version: '3.7'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.11.0
    volumes:
      - ${PWD}/configs/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elastic:/usr/share/elasticsearch/data/
    environment:
      ES_PATH_CONF: /usr/share/elasticsearch/config/
      xpack.security.enabled: true
      discovery.type: single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 8g
    env_file:
      - .env
    networks:
      - elk

  logstash:
    container_name: logstash
    image: logstash:8.11.0
    volumes:
      - ${PWD}/configs/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ${PWD}/configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ${PWD}/configs/logstash/pipelines:/usr/share/logstash/config/pipelines
    env_file:
      - .env
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: kibana:8.11.0
    depends_on:
      - elasticsearch
    volumes:
      - ${PWD}/configs/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    env_file:
      - .env
    networks:
      - elk

  beats:
    container_name: beats
    image: elastic/filebeat:8.11.0
    volumes:
      - ${PWD}/configs/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ${PWD}/host_metrics_app/:/host_metrics_app/
    networks:
      - elk
    depends_on:
      - elasticsearch

  nginx:
    container_name: nginx
    image: nginx:1.25.3
    volumes:
      - ${PWD}/nginx/kibana.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - elk
    depends_on:
      - kibana

networks:
  elk:

volumes:
  elastic:
