filebeat.inputs:
  - type: log
    enabled: true
    paths:     
    # path to the log file
      - /host_metrics_app/host_metrics_app.log
    fields:
      service: host_metrics_app

output.logstash: 
  hosts: ["logstash:5044"]